services:
  db:
    image: postgres:16-alpine
    container_name: bag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bag_user
      POSTGRES_PASSWORD: bag_local_password
      POSTGRES_DB: bag_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: